#!/usr/bin/env php
<?php

header("Content-Type:text/html;charset=utf-8");

include "vendor/autoload.php";
include "public/php_global/global.php";

$services = new \controller\FileReaderController();

//$services->indexAction();

$services->kuaishouAction();