#!/usr/bin/env php
<?php

define("ROOT_PATH", __DIR__);

header("Content-Type:text/html;charset=utf-8");

include "vendor/autoload.php";

$services = new \controller\FileReaderController();

$services->indexAction();